from pathlib import Path
p=Path('index.html'); s=p.read_text(encoding='utf-8')
r={
'.app{max-width:720px;margin:0 auto;padding:12px 12px 90px}':'.app{max-width:720px;margin:0 auto;padding:10px 10px 96px}',
'header{position:sticky;top:0;z-index:10;background:color-mix(in srgb,Canvas 94%,transparent);backdrop-filter:blur(10px);padding:8px 0 10px;border-bottom:1px solid color-mix(in srgb,CanvasText 14%,transparent)}':'header{position:sticky;top:0;z-index:10;background:color-mix(in srgb,Canvas 94%,transparent);backdrop-filter:blur(10px);padding:6px 0 8px;border-bottom:1px solid color-mix(in srgb,CanvasText 14%,transparent)}.compactHeader{display:grid;gap:6px}',
'h1{font-size:1.25rem;margin:0 0 8px}.sub{font-size:.82rem;opacity:.7;margin-bottom:8px}':'h1{font-size:1.15rem;margin:0}.sub{font-size:.76rem;opacity:.7;margin:0}',
'.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:12px 0}':'.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:7px;margin:10px 0}',
'.toolbar{display:flex;gap:7px;overflow:auto;padding-bottom:2px}':'.toolbar{display:flex;gap:7px;overflow:auto;padding-bottom:2px;scrollbar-width:none}.toolbar::-webkit-scrollbar{display:none}',
'.entry-note{font-size:.82rem;opacity:.8;margin-top:4px}':'.entry-note{font-size:.82rem;opacity:.8;margin-top:4px}.entry-actions{display:flex;gap:6px;margin-top:7px}.entry-actions button{padding:6px 8px;border-radius:9px;border:1px solid color-mix(in srgb,CanvasText 18%,transparent);background:color-mix(in srgb,CanvasText 4%,Canvas);color:CanvasText;font-size:.76rem}',
'.toast{position:fixed;':'.lastAction{margin:10px 0 0;padding:9px 10px;border:1px solid color-mix(in srgb,CanvasText 14%,transparent);border-radius:12px;font-size:.82rem}.recentActions{display:flex;gap:7px;overflow:auto;padding-bottom:2px}.recentActions button{white-space:nowrap;padding:8px 10px;border-radius:999px;border:1px solid color-mix(in srgb,CanvasText 18%,transparent);background:color-mix(in srgb,CanvasText 4%,Canvas);color:CanvasText}.backTop{position:fixed;right:14px;bottom:18px;z-index:50;border:1px solid color-mix(in srgb,CanvasText 18%,transparent);background:CanvasText;color:Canvas;border-radius:999px;padding:10px 13px;box-shadow:0 4px 16px color-mix(in srgb,CanvasText 18%,transparent)}.toast{position:fixed;',
'@media (min-width:540px){.rides{grid-template-columns:1fr 1fr}}':'@media (max-width:420px){.stats{grid-template-columns:repeat(2,1fr)}.stat{padding:8px}.seg button,.ride,.action{padding:10px}.search{padding:10px}}@media (min-width:540px){.rides{grid-template-columns:1fr 1fr}}',
'<header>\n  <h1>Disneyland Quick Check-In</h1>':'<header>\n  <div class="compactHeader">\n  <h1>Disneyland Quick Check-In</h1>',
'  <div id="backupPrompt" class="backupPrompt hidden"><b>Extra backup recommended</b><div class="muted">You have made 5 more check-ins since your last downloaded backup.</div><button class="action" onclick="backupNow()">Download backup now</button></div>\n</header>':'  <div id="backupPrompt" class="backupPrompt hidden"><b>Extra backup recommended</b><div id="backupDelta" class="muted">0 entries since your last downloaded backup.</div><button class="action" onclick="backupNow()">Download backup now</button></div>\n  </div>\n</header>',
'  <div class="stat"><b id="lastTime">—</b><span>last</span></div>\n</div>':'  <div class="stat"><b id="diningCount">0</b><span>dining</span></div>\n  <div class="stat"><b id="lastTime">—</b><span>last</span></div>\n</div>\n<div id="lastAction" class="lastAction muted">Nothing logged yet.</div>',
'<section>\n  <div class="section-title">Attractions</div>':'<section>\n  <div class="section-title">Recent</div>\n  <div id="recentActions" class="recentActions"><span class="muted">Recent actions will appear here.</span></div>\n</section>\n\n<section>\n  <div class="section-title">Attractions</div>',
'<div id="toast" class="toast"></div>':'<button id="backTop" class="backTop hidden" onclick="window.scrollTo({top:0,behavior:\'smooth\'})">↑ Top</button>\n<div id="toast" class="toast"></div>',
"function updateBackupPrompt(){const el=document.getElementById('backupPrompt');if(!el)return;const delta=memoryLog.length-(backupMeta().lastDownloadedCount||0);el.classList.toggle('hidden',delta<5)}":"function updateBackupPrompt(){const el=document.getElementById('backupPrompt'),txt=document.getElementById('backupDelta');if(!el)return;const delta=Math.max(0,memoryLog.length-(backupMeta().lastDownloadedCount||0));if(txt)txt.textContent=delta+' '+(delta===1?'entry':'entries')+' since your last downloaded backup.';el.classList.toggle('hidden',delta<5)}",
"function renderStats(){const log=loadLog();const rides=log.filter(x=>x.type!=='dining');document.getElementById('totalCount').textContent=rides.length;document.getElementById('uniqueCount').textContent=new Set(rides.map(x=>x.park+'|'+x.attraction)).size;document.getElementById('lastTime').textContent=log.length?fmtTime(log[log.length-1].timestamp):'—'}":"function renderStats(){const log=loadLog();const rides=log.filter(x=>x.type!=='dining'),dining=log.filter(x=>x.type==='dining');document.getElementById('totalCount').textContent=rides.length;document.getElementById('uniqueCount').textContent=new Set(rides.map(x=>x.park+'|'+x.attraction)).size;document.getElementById('diningCount').textContent=dining.length;document.getElementById('lastTime').textContent=log.length?fmtTime(log[log.length-1].timestamp):'—';const la=document.getElementById('lastAction');if(la){if(!log.length){la.textContent='Nothing logged yet.';la.classList.add('muted')}else{const x=log[log.length-1],name=x.type==='dining'?x.dining_location:x.attraction;la.textContent='Last: '+(x.type==='dining'?'Dining • ':'')+name+' • '+fmtTime(x.timestamp);la.classList.remove('muted')}}}",
'function renderAll(){renderRides();renderLog();renderStats();renderDiningRecent()}':'function renderAll(){renderRides();renderLog();renderStats();renderDiningRecent();renderRecentActions();updateBackupPrompt()}',
"window.addEventListener('visibilitychange'":"window.addEventListener('scroll',()=>{const b=document.getElementById('backTop');if(b)b.classList.toggle('hidden',window.scrollY<700)},{passive:true});\nwindow.addEventListener('visibilitychange'",
}
for a,b in r.items():
    if a not in s: raise SystemExit('missing marker: '+a[:80])
    s=s.replace(a,b,1)
add="function addDiningEntry(){const loc=document.getElementById('diningLocation').value.trim();if(!loc)return toast('Enter a dining location');const items=document.getElementById('diningItems').value.trim();const note=document.getElementById('diningNote').value.trim();const log=loadLog();log.push({id:crypto.randomUUID?crypto.randomUUID():String(Date.now())+Math.random(),type:'dining',dining_location:loc,items,timestamp:new Date().toISOString(),note});saveLog(log);document.getElementById('diningLocation').value='';document.getElementById('diningItems').value='';document.getElementById('diningNote').value='';renderAll();toast('Dining logged: '+loc)}"
helpers="""\nfunction findEntryIndex(id){return loadLog().findIndex(x=>String(x.id)===String(id))}\nfunction deleteEntry(id){const log=loadLog();const i=findEntryIndex(id);if(i<0)return;const x=log[i];if(!confirm('Delete this '+(x.type==='dining'?'dining entry':'attraction check-in')+'?'))return;log.splice(i,1);saveLog(log);renderAll();toast('Entry deleted')}\nfunction editEntry(id){const log=loadLog();const i=findEntryIndex(id);if(i<0)return;const x=log[i];if(x.type==='dining'){const loc=prompt('Dining location',x.dining_location||'');if(loc===null)return;const items=prompt('What did you get?',x.items||'');if(items===null)return;const note=prompt('Note',x.note||'');if(note===null)return;x.dining_location=loc.trim()||x.dining_location;x.items=items.trim();x.note=note.trim()}else{const name=prompt('Attraction / show',x.attraction||'');if(name===null)return;const note=prompt('Note',x.note||'');if(note===null)return;x.attraction=name.trim()||x.attraction;x.note=note.trim()}saveLog(log);renderAll();toast('Entry updated')}\nfunction repeatEntry(id){const x=loadLog().find(v=>String(v.id)===String(id));if(!x)return;if(x.type==='dining'){const log=loadLog();log.push({...x,id:crypto.randomUUID?crypto.randomUUID():String(Date.now())+Math.random(),timestamp:new Date().toISOString()});saveLog(log);renderAll();toast('Dining logged: '+x.dining_location)}else addCheckin(x.attraction,x.land,x.park)}"""
s=s.replace(add,add+helpers,1)
old="function renderLog(){const log=loadLog();const root=document.getElementById('log');root.innerHTML='';if(!log.length){root.innerHTML='<div class=\"muted\">No entries yet.</div>';return}for(const x of [...log].reverse()){const e=document.createElement('div');e.className='entry';e.innerHTML=`<div class=\"entry-top\"><div><div class=\"entry-kind\"></div><span class=\"entry-name\"></span><div class=\"ride-meta\"></div></div><div class=\"entry-time\"></div></div><div class=\"entry-note hidden\"></div>`;const dining=x.type==='dining';e.querySelector('.entry-kind').textContent=dining?'Dining':'Attraction';e.querySelector('.entry-name').textContent=dining?x.dining_location:x.attraction;e.querySelector('.ride-meta').textContent=dining?(x.items||'Meal / snack'):(x.park==='DL'?'Disneyland':'DCA')+(x.land?' • '+x.land:'');e.querySelector('.entry-time').textContent=fmtTime(x.timestamp);if(x.note){const n=e.querySelector('.entry-note');n.textContent=x.note;n.classList.remove('hidden')}root.appendChild(e)}}"
new="function renderLog(){const log=loadLog();const root=document.getElementById('log');root.innerHTML='';if(!log.length){root.innerHTML='<div class=\"muted\">Nothing logged yet. Tap an attraction or add a dining entry.</div>';return}for(const x of [...log].reverse()){const e=document.createElement('div');e.className='entry';e.innerHTML=`<div class=\"entry-top\"><div><div class=\"entry-kind\"></div><span class=\"entry-name\"></span><div class=\"ride-meta\"></div></div><div class=\"entry-time\"></div></div><div class=\"entry-note hidden\"></div><div class=\"entry-actions\"><button class=\"repeatBtn\">Repeat</button><button class=\"editBtn\">Edit</button><button class=\"deleteBtn\">Delete</button></div>`;const dining=x.type==='dining';e.querySelector('.entry-kind').textContent=dining?'Dining':'Attraction';e.querySelector('.entry-name').textContent=dining?x.dining_location:x.attraction;e.querySelector('.ride-meta').textContent=dining?(x.items||'Meal / snack'):(x.park==='DL'?'Disneyland':'DCA')+(x.land?' • '+x.land:'');e.querySelector('.entry-time').textContent=fmtTime(x.timestamp);if(x.note){const n=e.querySelector('.entry-note');n.textContent=x.note;n.classList.remove('hidden')}e.querySelector('.repeatBtn').onclick=()=>repeatEntry(x.id);e.querySelector('.editBtn').onclick=()=>editEntry(x.id);e.querySelector('.deleteBtn').onclick=()=>deleteEntry(x.id);root.appendChild(e)}}"
if old not in s: raise SystemExit('missing renderLog')
s=s.replace(old,new,1)
dining="function renderDiningRecent(){const dl=document.getElementById('recentDiningLocations');if(!dl)return;const seen=new Set();dl.innerHTML='';for(const x of [...loadLog()].reverse()){if(x.type!=='dining'||!x.dining_location||seen.has(x.dining_location))continue;seen.add(x.dining_location);const o=document.createElement('option');o.value=x.dining_location;dl.appendChild(o);if(seen.size>=8)break}}"
recent="""\nfunction renderRecentActions(){const root=document.getElementById('recentActions');if(!root)return;root.innerHTML='';const seen=new Set(),recent=[];for(const x of [...loadLog()].reverse()){const key=x.type==='dining'?'d|'+x.dining_location:'a|'+x.park+'|'+x.attraction;if(seen.has(key))continue;seen.add(key);recent.push(x);if(recent.length>=5)break}if(!recent.length){root.innerHTML='<span class=\"muted\">Recent actions will appear here.</span>';return}for(const x of recent){const b=document.createElement('button');b.textContent='↻ '+(x.type==='dining'?x.dining_location:x.attraction);b.onclick=()=>repeatEntry(x.id);root.appendChild(b)}}"""
s=s.replace(dining,dining+recent,1)
p.write_text(s,encoding='utf-8')